Repository GDSC-CAU/GDSC-SPACE, pull requests merged in 2023-09, with the labels that each got.

#86 [FIX] 각종 API 관련 Issue 해결
  package.json
  pnpm-lock.yaml
  src/app/api/blog/getList/[type]/route.ts
  src/app/api/event/getList/route.ts
  src/app/api/members/getList/[year]/route.ts
  src/app/members/[year]/page.tsx
  src/utils/FirebaseUtil.ts
Labels: fix

#87 [DEV] blog detail
  src/app/blog/[type]/[id]/page.tsx
  src/app/blog/[type]/layout.tsx
  src/app/blog/[type]/page.tsx
  src/components/common/PageHeader.tsx
Labels: dev

#88 [FIX] Resolve Merge Conflict
  next.config.js
  package.json
  pnpm-lock.yaml
  src/app/api/blog/getDetail/[type]/[id]/route.ts
  src/app/blog/[type]/[id]/_components/BlogNavigationButtons.tsx
  src/app/blog/[type]/[id]/_components/DevPostView.tsx
  src/app/blog/[type]/[id]/_components/NotionRenderer.tsx
  src/app/blog/[type]/[id]/_components/ProjectPostView.tsx
  src/app/blog/[type]/[id]/_components/index.ts
  src/app/blog/[type]/[id]/loading.tsx
  src/app/blog/[type]/[id]/page.tsx
  src/app/blog/[type]/layout.tsx
  src/app/blog/[type]/page.tsx
  src/app/blog/_components/BlogArticleView.tsx
  src/app/blog/_components/BlogHeader.tsx
  src/app/events/page.tsx
  src/components/common/Link.tsx
  src/components/common/PageHeader.tsx
  src/components/common/ThumbnailCard.tsx
  src/interfaces/Common.ts
  src/styles/nord.css
  src/utils/notion/BlogPost.ts
  src/utils/notion/NotionError.ts
  src/utils/notion/PageManager.ts
  src/utils/notion/index.ts
  tailwind.config.js
Labels: fix

#92 [DEV] Event 페이지 mobile UI 구현
  src/app/events/_components/EventCardDesktop.tsx
  src/app/events/_components/TimeLineCard.tsx
  src/app/events/page.tsx
Labels: dev

#90 [DEV] 멤버 데탑 페이지 수정사항 완료
  src/app/members/[year]/layout.tsx
  src/app/members/_components/MemberCard.tsx
  src/app/members/_components/MemberHorizontalScrollView.tsx
  tailwind.config.js
Labels: fix, dev

#93 [DEV] Event 페이지 mobile UI 구현
  src/app/events/_components/EventCard.tsx
  src/app/events/page.tsx
Labels: dev

#95 [DEV] Blog Tag 및 Event API 연동
  src/app/api/blog/getList/[type]/route.ts
  src/app/api/event/getDetail/[id]/route.ts
  src/app/blog/[type]/[id]/_components/DevPostView.tsx
  src/app/blog/[type]/[id]/_components/ProjectPostView.tsx
  src/app/blog/[type]/[id]/_components/index.ts
  src/app/events/[id]/page.tsx
  src/app/events/page.tsx
  src/interfaces/Common.ts
  src/utils/FirebaseUtil.ts
  src/utils/notion/NotionRenderer.tsx
Labels: dev

#96 [DEV] MemberPage_Mobile 구현 완료
  src/app/members/[year]/layout.tsx
  src/app/members/_components/MemberCard.tsx
  src/app/members/_components/MemberContact.tsx
  src/app/members/_components/MemberHorizontalScrollView.tsx
  src/app/members/_components/MemberRoleIcon.tsx
  tailwind.config.js
Labels: dev

#98 [FIX] member layout
  src/app/members/[year]/layout.tsx
  src/app/members/[year]/page.tsx
  src/app/members/_components/MemberHorizontalScrollView.tsx
Labels: fix

#100 [FIX] Blog 및 Member 로직 이슈 해결
  src/app/_components/sections/projects/ProjectDesktopCard.tsx
  src/app/api/blog/getDetail/[type]/[id]/route.ts
  src/utils/notion/BlogPost.ts
Labels: fix

#102 [FIX] MemberPage, MainPage
  src/app/_components/sections/introduction/WhoAreWe.tsx
  src/app/members/[year]/layout.tsx
  src/app/members/[year]/page.tsx
  src/app/members/_components/MemberAvatar.tsx
  src/app/members/_components/MemberHorizontalScrollView.tsx
Labels: fix

#104 [FIX] main페이지 project카드 글씨/사진 잘림
  src/app/_components/sections/projects/ProjectDesktopCard.tsx
  src/app/_components/sections/projects/ProjectMobileCard.tsx
  src/app/_components/sections/projects/ProjectsSection.tsx
Labels: fix

#106 [FIX] timeline card invisible error
  src/app/events/_components/TimeLineCard.tsx
Labels: fix

#108 fix: react-notion-x collection component error
  src/utils/notion/NotionRenderer.tsx
Labels: fix

#110 [FIX] timeline card width overflow issue
  src/app/events/_components/TimeLineCard.tsx
Labels: fix

#112 [FIX] MemberPage fix
  src/app/members/[year]/layout.tsx
  src/app/members/_components/MemberHorizontalScrollView.tsx
Labels: fix

#114 [DEV] Favicon 적용 및 더미파일 제거
  public/events/cardtest.png
  public/favicon.svg
  src/app/layout.tsx
Labels: dev

#116 [REFACTOR] timeline card color 순서
  src/app/_components/sections/timelines/TimelineCardView.tsx
Labels: refactor

#118 [DEV] 배포시스템 대응 URL 분기처리
  src/utils/fetcher.ts
Labels: dev

#120 [FIX] Prerender 관련 Fetch Issue
  src/app/events/page.tsx
  src/app/page.tsx
Labels: fix

#124 [FIX] mobile `x-overflow` 문제 및 desktop 잘리는 현상
  src/app/_components/sections/projects/ProjectDesktopCard.tsx
  src/app/_components/sections/projects/ProjectsSection.tsx
  src/app/page.tsx
Labels: fix

#126 [FIX] event card location 수정
  src/app/events/layout.tsx
  src/app/events/page.tsx
Labels: fix

#127 [FIX] 이벤트 상세 글 join 버튼 수정
  src/app/events/[id]/page.tsx
Labels: fix

#129 [FIX] Blog 페이지 및 Footer 텍스트 오타 수정
  src/app/blog/_components/BlogHeader.tsx
  src/components/common/Footer.tsx
Labels: fix

#131 [FIX] timelinecard margin
  src/app/events/_components/TimeLineCard.tsx
Labels: fix

#135 [FIX] post createdAt 기반 내림차순 정렬
  src/interfaces/Common.ts
  src/utils/notion/BlogPost.ts
Labels: fix, refactor

#136 [FIX] Event List 정렬기준 변경
  src/utils/FirebaseUtil.ts
Labels: fix, refactor
