Repository GDSC-CAU/GDSC-SPACE, pull requests merged in 2025-02, with the labels that each got.

#145 [FIX] 멤버 이미지 연동 에러
  next.config.js
  src/app/members/_components/MemberCard.tsx
Labels: fix

#152 [FIX] 멤버 카드 뒷면 contact 관련
  src/app/members/_components/MemberCard.tsx
  src/app/members/_components/MemberContact.tsx
Labels: fix

#155 [DEV] 4기 멤버 업데이트 및 Role Tag 변경
  src/app/members/[year]/layout.tsx
  src/app/members/_components/MemberRoleIcon.tsx
  src/components/icons/Organizer.tsx
  src/components/icons/TeamMember.tsx
  src/components/icons/index.ts
  src/interfaces/Common.ts
Labels: dev

#156 [FIX] 모바일 글자 잘림 이슈 수정
  src/app/members/_components/MemberCard.tsx
  src/app/members/_components/MemberContact.tsx
Labels: fix

#161 [FIX] Members 페이지 네비게이션 변경
  src/app/_components/navBar/NavBarDesktop.tsx
  src/app/members/page.tsx
  src/components/common/Link.tsx
Labels: fix

#162 [REFACTOR] icon 추가 및 svgr 웹팩 설정
  jest.config.mjs
  next.config.js
  package.json
  pnpm-lock.yaml
  src/app/members/_components/MemberRoleIcon.tsx
  src/components/icons/Organizer.tsx
  src/components/icons/TeamMember.tsx
  src/components/icons/index.ts
  src/styles/icons/SVGCore.svg
  src/styles/icons/SVGGithub.svg
  src/styles/icons/SVGLead.svg
  src/styles/icons/SVGOrg.svg
  src/styles/icons/SVGTm.svg
  src/styles/icons/index.ts
Labels: refactor
